# Generated by Django 5.2 on 2026-05-22 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('title',), 'verbose_name_plural': 'Categorías'},
        ),
    ]
